# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: push-dev

on:
  push:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.4.0
      - name: Set up JDK 16
        uses: actions/setup-java@v3.0.0
        with:
          java-version: '16'
          distribution: 'adopt'
      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        if: success()
        with:
          name: CrossplatForms-Spigot.jar
          path: spigot/build/libs/CrossplatForms-Spigot.jar
          retention-days: 15
